import 'package:ip2proxy/ip2proxy.dart';
import 'package:test/test.dart';

void main() {
  var notSupported =
      'This parameter is unavailable for selected data file. Please upgrade the data file.';
  var px12BINFile =
      r'C:\your_folder\IP2PROXY-IP-PROXYTYPE-COUNTRY-REGION-CITY-ISP-DOMAIN-USAGETYPE-ASN-LASTSEEN-THREAT-RESIDENTIAL-PROVIDER-FRAUDSCORE.BIN';
  group('Test General', () {
    test('Google IPv4', () async {
      var ipx = IP2Proxy(databasePath: px12BINFile);
      var result = await ipx.getAll('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.isProxy, 2);
      expect(result.proxyType, 'DCH');
      expect(result.countryShort, 'US');
      expect(result.countryLong, 'United States of America');
      expect(result.region, 'California');
      expect(result.city, 'Mountain View');
      expect(result.isp, 'Google LLC');
      expect(result.domain, 'google.com');
      expect(result.usageType, 'DCH');
      expect(result.asn, '15169');
      expect(result.asName, 'Google LLC');
      expect(result.lastSeen, '17');
      expect(result.threat, '-');
      expect(result.provider, '-');
      expect(result.fraudScore, '0');
    });
    test('Yahoo IPv4', () async {
      var ipx = IP2Proxy(databasePath: px12BINFile);
      var result = await ipx.getAll('8.3.34.0');
      expect(result.ipAddress, '8.3.34.0');
      expect(result.isProxy, 2);
      expect(result.proxyType, 'SES');
      expect(result.countryShort, 'US');
      expect(result.countryLong, 'United States of America');
      expect(result.region, 'California');
      expect(result.city, 'Sunnyvale');
      expect(result.isp, 'Yahoo! Inc.');
      expect(result.domain, 'yahoo.com');
      expect(result.usageType, 'SES');
      expect(result.asn, '1');
      expect(result.asName, 'Level 3 Parent LLC');
      expect(result.lastSeen, '17');
      expect(result.threat, '-');
      expect(result.provider, '-');
      expect(result.fraudScore, '0');
    });
    test('NetAssist', () async {
      var ipx = IP2Proxy(databasePath: px12BINFile);
      var result = await ipx.getAll('2a01:d0:dc08:8d21:e437:10a6:2e0a:e647');
      expect(result.ipAddress, '2A01:00D0:DC08:8D21:E437:10A6:2E0A:E647');
      expect(result.isProxy, 1);
      expect(result.proxyType, 'VPN');
      expect(result.countryShort, 'UA');
      expect(result.countryLong, 'Ukraine');
      expect(result.region, 'Kyiv');
      expect(result.city, 'Kyiv');
      expect(result.isp, 'NetAssist Free IPv6 Tunnel Broker');
      expect(result.domain, 'netassist.ltd.gi');
      expect(result.usageType, 'DCH');
      expect(result.asn, '8772');
      expect(result.asName, 'NetAssist LLC');
      expect(result.lastSeen, '17');
      expect(result.threat, '-');
      expect(result.provider, 'NetAssist VPN');
      expect(result.fraudScore, '95');
    });
  }, skip: 'Skipping General tests.');
  group('Test 6to4', () {
    test('Google', () async {
      var ipx = IP2Proxy(databasePath: px12BINFile);
      var result = await ipx.getAll('2002:808:808::');
      expect(result.ipAddress, '2002:808:808::');
      expect(result.isProxy, 2);
      expect(result.proxyType, 'DCH');
      expect(result.countryShort, 'US');
      expect(result.countryLong, 'United States of America');
      expect(result.region, 'California');
      expect(result.city, 'Mountain View');
      expect(result.isp, 'Google LLC');
      expect(result.domain, 'google.com');
      expect(result.usageType, 'DCH');
      expect(result.asn, '15169');
      expect(result.asName, 'Google LLC');
      expect(result.lastSeen, '17');
      expect(result.threat, '-');
      expect(result.provider, '-');
      expect(result.fraudScore, '0');
    });
  }, skip: 'Skipping 6to4 tests.');
  group('Test Teredo', () {
    test('Yahoo', () async {
      var ipx = IP2Proxy(databasePath: px12BINFile);
      var result = await ipx.getAll('2001:0000:4136:e378:8000:63bf:f7fc:ddff');
      expect(result.ipAddress, '2001:0000:4136:E378:8000:63BF:F7FC:DDFF');
      expect(result.isProxy, 2);
      expect(result.proxyType, 'SES');
      expect(result.countryShort, 'US');
      expect(result.countryLong, 'United States of America');
      expect(result.region, 'California');
      expect(result.city, 'Sunnyvale');
      expect(result.isp, 'Yahoo! Inc.');
      expect(result.domain, 'yahoo.com');
      expect(result.usageType, 'SES');
      expect(result.asn, '1');
      expect(result.asName, 'Level 3 Parent LLC');
      expect(result.lastSeen, '17');
      expect(result.threat, '-');
      expect(result.provider, '-');
      expect(result.fraudScore, '0');
    });
  }, skip: 'Skipping Teredo tests.');
  group('Test Individual Fields', () {
    test('Test Is Proxy', () async {
      var ipx = IP2Proxy(databasePath: px12BINFile);
      var result = await ipx.getIsProxy('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.isProxy, 2);
      expect(result.proxyType, 'DCH');
      expect(result.countryShort, 'US');
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.domain, notSupported);
      expect(result.usageType, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
      expect(result.lastSeen, notSupported);
      expect(result.threat, notSupported);
      expect(result.provider, notSupported);
      expect(result.fraudScore, notSupported);
    });
    test('Test Proxy Type', () async {
      var ipx = IP2Proxy(databasePath: px12BINFile);
      var result = await ipx.getProxyType('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.isProxy, 2);
      expect(result.proxyType, 'DCH');
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.domain, notSupported);
      expect(result.usageType, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
      expect(result.lastSeen, notSupported);
      expect(result.threat, notSupported);
      expect(result.provider, notSupported);
      expect(result.fraudScore, notSupported);
    });
    test('Test Country Short', () async {
      var ipx = IP2Proxy(databasePath: px12BINFile);
      var result = await ipx.getCountryShort('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.isProxy, 1);
      expect(result.proxyType, notSupported);
      expect(result.countryShort, 'US');
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.domain, notSupported);
      expect(result.usageType, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
      expect(result.lastSeen, notSupported);
      expect(result.threat, notSupported);
      expect(result.provider, notSupported);
      expect(result.fraudScore, notSupported);
    });
    test('Test Country Long', () async {
      var ipx = IP2Proxy(databasePath: px12BINFile);
      var result = await ipx.getCountryLong('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.isProxy, 1);
      expect(result.proxyType, notSupported);
      expect(result.countryShort, notSupported);
      expect(result.countryLong, 'United States of America');
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.domain, notSupported);
      expect(result.usageType, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
      expect(result.lastSeen, notSupported);
      expect(result.threat, notSupported);
      expect(result.provider, notSupported);
      expect(result.fraudScore, notSupported);
    });
    test('Test Region', () async {
      var ipx = IP2Proxy(databasePath: px12BINFile);
      var result = await ipx.getRegion('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.isProxy, 1);
      expect(result.proxyType, notSupported);
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, 'California');
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.domain, notSupported);
      expect(result.usageType, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
      expect(result.lastSeen, notSupported);
      expect(result.threat, notSupported);
      expect(result.provider, notSupported);
      expect(result.fraudScore, notSupported);
    });
    test('Test City', () async {
      var ipx = IP2Proxy(databasePath: px12BINFile);
      var result = await ipx.getCity('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.isProxy, 1);
      expect(result.proxyType, notSupported);
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, 'Mountain View');
      expect(result.isp, notSupported);
      expect(result.domain, notSupported);
      expect(result.usageType, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
      expect(result.lastSeen, notSupported);
      expect(result.threat, notSupported);
      expect(result.provider, notSupported);
      expect(result.fraudScore, notSupported);
    });
    test('Test ISP', () async {
      var ipx = IP2Proxy(databasePath: px12BINFile);
      var result = await ipx.getIsp('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.isProxy, 1);
      expect(result.proxyType, notSupported);
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, 'Google LLC');
      expect(result.domain, notSupported);
      expect(result.usageType, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
      expect(result.lastSeen, notSupported);
      expect(result.threat, notSupported);
      expect(result.provider, notSupported);
      expect(result.fraudScore, notSupported);
    });
    test('Test Domain', () async {
      var ipx = IP2Proxy(databasePath: px12BINFile);
      var result = await ipx.getDomain('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.isProxy, 1);
      expect(result.proxyType, notSupported);
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.domain, 'google.com');
      expect(result.usageType, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
      expect(result.lastSeen, notSupported);
      expect(result.threat, notSupported);
      expect(result.provider, notSupported);
      expect(result.fraudScore, notSupported);
    });
    test('Test Usage Type', () async {
      var ipx = IP2Proxy(databasePath: px12BINFile);
      var result = await ipx.getUsageType('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.isProxy, 1);
      expect(result.proxyType, notSupported);
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.domain, notSupported);
      expect(result.usageType, 'DCH');
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
      expect(result.lastSeen, notSupported);
      expect(result.threat, notSupported);
      expect(result.provider, notSupported);
      expect(result.fraudScore, notSupported);
    });
    test('Test ASN', () async {
      var ipx = IP2Proxy(databasePath: px12BINFile);
      var result = await ipx.getAsn('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.isProxy, 1);
      expect(result.proxyType, notSupported);
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.domain, notSupported);
      expect(result.usageType, notSupported);
      expect(result.asn, '15169');
      expect(result.asName, notSupported);
      expect(result.lastSeen, notSupported);
      expect(result.threat, notSupported);
      expect(result.provider, notSupported);
      expect(result.fraudScore, notSupported);
    });
    test('Test AS', () async {
      var ipx = IP2Proxy(databasePath: px12BINFile);
      var result = await ipx.getAsName('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.isProxy, 1);
      expect(result.proxyType, notSupported);
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.domain, notSupported);
      expect(result.usageType, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, 'Google LLC');
      expect(result.lastSeen, notSupported);
      expect(result.threat, notSupported);
      expect(result.provider, notSupported);
      expect(result.fraudScore, notSupported);
    });
    test('Test Last Seen', () async {
      var ipx = IP2Proxy(databasePath: px12BINFile);
      var result = await ipx.getLastSeen('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.isProxy, 1);
      expect(result.proxyType, notSupported);
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.domain, notSupported);
      expect(result.usageType, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
      expect(result.lastSeen, '17');
      expect(result.threat, notSupported);
      expect(result.provider, notSupported);
      expect(result.fraudScore, notSupported);
    });
    test('Test Threat', () async {
      var ipx = IP2Proxy(databasePath: px12BINFile);
      var result = await ipx.getThreat('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.isProxy, 1);
      expect(result.proxyType, notSupported);
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.domain, notSupported);
      expect(result.usageType, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
      expect(result.lastSeen, notSupported);
      expect(result.threat, '-');
      expect(result.provider, notSupported);
      expect(result.fraudScore, notSupported);
    });
    test('Test Provider', () async {
      var ipx = IP2Proxy(databasePath: px12BINFile);
      var result = await ipx.getProvider('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.isProxy, 1);
      expect(result.proxyType, notSupported);
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.domain, notSupported);
      expect(result.usageType, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
      expect(result.lastSeen, notSupported);
      expect(result.threat, notSupported);
      expect(result.provider, '-');
      expect(result.fraudScore, notSupported);
    });
    test('Test Fraud Score', () async {
      var ipx = IP2Proxy(databasePath: px12BINFile);
      var result = await ipx.getFraudScore('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.isProxy, 1);
      expect(result.proxyType, notSupported);
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.domain, notSupported);
      expect(result.usageType, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
      expect(result.lastSeen, notSupported);
      expect(result.threat, notSupported);
      expect(result.provider, notSupported);
      expect(result.fraudScore, '0');
    });
  }, skip: 'Skipping Individual Field tests first.');
}
